export type DifficultyLevel = "beginner" | "intermediate" | "advanced";
export type ResourceType = "pdf" | "document" | "link" | "download" | "interactive";
export type TopicContentType = "video" | "document" | "interactive" | "quiz" | "mixed";

export interface CourseContent {
  id: string;
  title: string;
  instructor: string;
  description: string;
  totalTopics: number;
  estimatedDuration: number; // in hours
  difficulty: DifficultyLevel;
  category: string;
  tags: string[];
}

export interface Resource {
  id: string;
  title: string;
  type: ResourceType;
  url: string;
  size?: number;
  downloadable: boolean;
  description?: string;
}

export interface VideoChapter {
  id: string;
  title: string;
  startTime: number; // seconds
  endTime: number; // seconds
  summary?: string;
}

export interface TranscriptSegment {
  id: string;
  startTime: number;
  endTime: number;
  text: string;
  highlighted?: boolean;
}

export interface Transcript {
  id: string;
  language: string;
  isAutoGenerated?: boolean;
  segments: TranscriptSegment[];
}

export interface VideoQuality {
  id: string;
  label: string;
  resolution: string;
  bitrate: number;
  url: string;
}

export interface Bookmark {
  id: string;
  label: string;
  note: string;
  timestamp: number;
  createdAt: string;
}

export interface QuizResult {
  quizId: string;
  score: number;
  totalQuestions: number;
  completedAt: string;
}

export interface VideoContent {
  id: string;
  title: string;
  url: string;
  duration: number; // seconds
  thumbnail: string;
  chapters: VideoChapter[];
  transcripts: Transcript[];
  quality: VideoQuality[];
  resumePosition?: number;
}

export interface Topic {
  id: string;
  title: string;
  description: string;
  order: number;
  estimatedDuration: number; // in minutes
  contentType: TopicContentType;
  isCompleted: boolean;
  isLocked: boolean;
  resources: Resource[];
  learningObjectives: string[];
  relatedTopics?: string[];
  interactiveContent?: Array<{ id: string; title: string; type: string; status: "pending" | "completed" }>;
}

export interface LearningProgress {
  courseId: string;
  topicId: string;
  timeSpent: number; // seconds
  lastPosition: number; // seconds for video/audio content
  completionPercentage: number;
  notesCount: number;
  bookmarks: Bookmark[];
  quizScores: QuizResult[];
  streakCount?: number;
  achievements?: string[];
}

export interface DiscussionThread {
  id: string;
  topicId: string;
  title: string;
  replies: Array<{
    id: string;
    author: string;
    role: "student" | "instructor";
    content: string;
    createdAt: string;
    upvotes?: number;
  }>;
}

export interface LearningPreference {
  prefersTranscript: boolean;
  prefersHighContrast: boolean;
  playbackSpeed: number;
  theme: "light" | "dark" | "contrast";
  layoutDensity: "comfortable" | "compact";
}

export interface TopicRecommendation {
  topicId: string;
  reason: string;
  priority: "high" | "medium" | "low";
}
